# Snakefile

# Global variables (could be in a config file)

import os, sys

work_dir = os.getcwd()
scripts_dir = os.path.join(work_dir, "scripts")
data_dir = os.path.join(work_dir, "data")
intermediate_dir = os.path.join(work_dir, "intermediate_data")
sample = ["IND"]

# Rule to fetch weather data using PCSE
rule wdp:
    output:
        "intermediate_data/wdp_IND.pkl"
    shell:
        "python scripts/fetch_weather.py > {output} "

# Rule source soil 
rule soild:
    shell:
        "python scripts/fetch_soil.py"

# Rule to source crop 


# Rule to source site

